version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ..
      dockerfile: config/docker/Dockerfile
      target: runner
    container_name: fare-calculator-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      # Updated to use PostgreSQL environment variables
      DB_USER: postgres
      DB_HOST: database-1.cboacuqkk7st.ap-northeast-1.rds.amazonaws.com
      DB_NAME: mc_taxi_calculator
      DB_PASSWORD: D78SIf4QLaAATWWTMABu
      DB_PORT: 5432
      DB_SSL: false
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fare-calculator-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ..
      dockerfile: config/docker/Dockerfile.frontend
      target: runner
    container_name: fare-calculator-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - fare-calculator-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: fare-calculator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - fare-calculator-network

networks:
  fare-calculator-network:
    driver: bridge
