version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mc-taxi-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mc_taxi_calculator
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ../../mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mc-taxi-network

  # Backend API
  backend:
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile
      target: runner
    container_name: mc-taxi-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb+srv://bilbaojohnmichael_db_user:WausBHorb5bL8Iyu@mctaxi.usdejer.mongodb.net/?retryWrites=true&w=majority&appName=MCTAXI
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ../../logs:/app/logs
    networks:
      - mc-taxi-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  mc-taxi-network:
    driver: bridge
